### ISSUE TITLE
2 Things. One is non-related

### ISSUE THREAD

**Issue by IICoffyII** [jigsaw-4277821/PE-0.5.1-ExtraKeys-Android#1]
### Describe your bug here.

1st - This thing seems to get extremely laggy whenever it isn't 4K.
2nd - On the Psych Engine 0.5 source code, I am unable to do anything, they never save, the workflow always fails.
Thank you for the time.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Here and another (Psych Engine 5.0)...

**Comment by Fakekris** [comment]
well, when i accepted the storage permission, there it was saying "try copying assets/assets and assets/mods of apk to your internal storage app directory "i don't know if that's how you spell it* but I'm having problems where I put these files, is there any solution?

**Comment by jigsaw-4277821** [comment]
You need a OTG keyboard or wireless

**Comment by jigsaw-4277821** [comment]
No longer
